name: Update README with Markdown Tree

on:
  push:
    branches:
      - main  # Adjust if your default branch has a different name

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          github_token: ${{ secrets.ACCESS_TOKEN }}


    - name: Setup environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate Markdown Tree
      run: |
        chmod u+x ./generate_tree.sh
        ./generate_tree.sh . > README.md

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Your Name
        author_email: mail@example.com
        message: 'Your commit message'
        add: '*.md'

