name: Update README with Markdown Tree

on:
  push:
    branches:
      - main  # Adjust if your default branch has a different name

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate Markdown Tree
      run: |
        chmod u+x ./generate_tree.sh
        ./generate_tree.sh . > README.md

    - name: Commit README
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add README.md
        git commit -m "Automatically update README with Markdown tree" -a || echo "No changes to commit"
        git push

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Your Name
        author_email: mail@example.com
        message: 'Your commit message'
        add: '*.md'

